### ISSUE TITLE
Syntax error in `hdf5.mak`?

### ISSUE THREAD

**Issue by jamesgabbard** [thomasgillis/dbs#11]
I don't know `Make` at all, but I was unable to submit a job until changing
```
ifdef ZLIB_VER
    HDF5_ZLIB_DEP = --with-zlib=$(PREFIX)
endif
```
to
```
ifdef ZLIB_VER
HDF5_ZLIB_DEP = --with-zlib=$(PREFIX)
endif
```
(note the indents). If this seems correct, I can open a PR with the small fix.

**Comment by thomasgillis** [comment]
good catch, should be fixed in #12
